CREATE TABLE IF NOT EXISTS documentos (
    id SERIAL PRIMARY KEY,
    caminho VARCHAR(255) NOT NULL,
    id_user INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_documentos_users FOREIGN KEY (id_user)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
